### ISSUE TITLE
Resource Not Found upon installation

### ISSUE THREAD

**Issue by brimwats** [YunoHost-Apps/shiori_ynh#26]
My YunoHost server
Hardware: Dell R720
YunoHost version: Powered by [YunoHost](https://yunohost.org/) 11.1.21.4 (stable).
I have access to my server : SSH, direct access
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : not really. I have a RAID server, where /home = ~2TB and /var = 20TB so most of my storage needs to be on /var

I installed shiori but when I go to the subdomain it is on I get no resource found 

logs:

https://paste.yunohost.org/raw/ugoveqanal

**Comment by brimwats** [comment]
I don't know what's up with the reoccurring portainer.main line; portainer is not installed

**Comment by link-leo** [comment]
I have the same issue.

- Logs indicate Shiori service is running fine.
- `sudo yunohost service status shiori` shows `status: running`
- This is a fresh install on YNH 11.2.2

**Comment by ericgaspar** [comment]
I can't reproduce this issue. Fresh install on subdomain ( YNH 11.2.2) and it works.
Please add your setup and logs

**Comment by link-leo** [comment]
### My YunoHost server

**Hardware:** Mini PC (AMD)
**YunoHost version:**  11.2.2
**I have access to my server :** Through SSH and through the webadmin
**Are you in a special context or did you perform some particular tweaking on your YunoHost instance?:** no

https://paste.yunohost.org/lagedosowe

**Comment by ericgaspar** [comment]
is it installed on a subdomain/subfolder? what is the error on screen?

**Comment by link-leo** [comment]
It is installed on a main domain with a subdirectory as in mydomain.tld/bmk and there is no error, I simply access mydomain.tld/bmk and get a single line of text that says `Resource Not Found` and there are no logs or statuses indicating any error that I can see, though I will run any command or fetch any log you can detail.

**Comment by ericgaspar** [comment]
Ok, I think the problem is in the part of systemd sandboxing options `/etc/systemd/system/shiori.service`. not sure which line is the culprit. you can comment out lines between 15 and 45. #28 should fix temporarily the problem. (ideally we should find the problematic line and leave the rest of the configuration...)

**Comment by ericgaspar** [comment]
fixed with https://github.com/YunoHost-Apps/shiori_ynh/pull/28

**Comment by link-leo** [comment]
Ran an upgrade to latest version through the YNH webadmin, did not resolve the problem. Manually restarted the Shiori service, did not resolve the problem. Suggestions?

**Comment by ericgaspar** [comment]
what version did you update to? 1.5.5~ynh2

**Comment by link-leo** [comment]
```
$ sudo yunohost app info shiori
description: Simple bookmark manager
domain_path: mydomain.tld/bmk
name: Shiori
version: 1.5.5~ynh1
```

**Comment by ericgaspar** [comment]
the 1.5.5~ynh2 version is not yet available to download because it has not been validated yet by the CI.

**Comment by link-leo** [comment]
Oh, I saw the upgrade and thought that was already the one. I'll be patient.

**Comment by ericgaspar** [comment]
or in a terminal
`sudo yunohost app upgrade shiori -u https://github.com/YunoHost-Apps/shiori_ynh`

**Comment by link-leo** [comment]
This appears to have worked. Thanks for the quick resolution!
